--- 
abstract: "Simple Access to screenshot-tool thumbalizr "
author: 
  - Thomas Fahle <cpan@thomas-fahle.de>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: ThumbalizrSimple
no_index: 
  directory: 
    - inc
    - t
version: 0.01
